### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by kawilliams8**
#### What’s this PR do?

Adds the README with API documentation.

#### Where should the reviewer start?

This file is completely new. There are no changes in existing files.

#### How should this be manually tested?

Please proofread for grammar and missed details.

#### Any background context you want to provide?

I looked into adding a link to the Clubhouse board, but they can't be made public from free accounts.

#### What are the relevant tickets?

https://app.clubhouse.io/palettepicker/story/73/back-end-readme

#### Screenshots (if appropriate)

N/A

#### Questions:

None at this time.

### CODE REVIEW

**Comment by kawilliams8** [comment]
Just remembered that I wanted to add a schema diagram to this document. I will push it to this branch if I get it done before you've had a chance to merge.

**Comment by davidagitlen** [comment]
Ok, great, thank you! I will wait until I see that to merge it.

**Comment by kawilliams8** [comment]
Image added! I had to edit this in the github UI to get the correct image URL, so there's a couple extra commits that can probably be squashed. @davidagitlen

**Review by davidagitlen — COMMENTED** [review]
Great work, thank you so much!

**Pull request merged**
